### ISSUE TITLE
Split protocol and real-world data

### ISSUE THREAD

**Issue by jyunlee** [microsoft/SimpleEgo#4]
Hello, thanks for the nice work!
Do you have plans to release the train / val / test split protocol and also the real-world data used for evaluation?

**Comment by friggog** [comment]
Hi - we use 10% of the synthetic data for validation, this subset is randomly selected. All of the real-world evaluations featured in the paper are on public datasets that you can download from the original sources, we cannot redistribute them - the citations are provided in each case from which you should be able to find the download instructions.
